apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s/discuz/db
    ##这里的IP，是NFS server的IP
    server: 192.168.2.4
